arch: NestedUNet
batch_size: 1
dataset: ''
deep_supervision: false
early_stopping: -1
epochs: 500
factor: 0.1
gamma: 0.1
img_ext: .dcm
input_channels: 3
input_h: 512
input_w: 512
loss: BCEDiceLoss
lr: 0.001
mask_ext: .dcm
milestones: 1,2
min_lr: 0.001
momentum: 0.9
name: _NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 4
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
